export enum RedisActionsEnum {
    REQUEST = "REQUEST",
    BLOCKREQUEST = "BLOCK::REQUEST",
    BLOCKLOGIN = "BLOCK::LOGIN",
    BLOCKFORETPASSWORD = "BLOCK::FOGET::PASSWORD",
    BLOCKTWOSTEPVERIFICATION = "BLOCK::TWO::STEP::VERIFICATION",
}
export enum RedisTypeEnum {
    CONFIRMEMAIL = "Confirm::Email",
    LOGIN = "LOGIN",
    FORGETPASSWORD = "FORGET::PASSWORD",
    RESETPASSWORD = "RESET::PASSWORD",
    TWOSTEPVERIFICATION = "TWO::STEP::VERIFICATION",
}